### ISSUE TITLE
Stack trace when loading admin settings tree

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_passwordvalidator#11]
Exception - Call to undefined function config_checker()

More information about this error

×Debug info: 
Error code: generalexceptionmessage
×Stack trace:
line 101 of /admin/tool/passwordvalidator/settings.php: Error thrown
line 81 of /lib/classes/plugininfo/tool.php: call to include()
line 599 of /admin/settings/plugins.php: call to core\plugininfo\tool->load_settings()
line 8000 of /lib/adminlib.php: call to require()
line 7887 of /lib/adminlib.php: call to admin_get_root()
line 24 of /admin/search.php: call to admin_externalpage_setup()

**Comment by Peterburnett** [comment]
Fixed in PR #17. Closing
