### ISSUE TITLE
Refactor password testing tool into it's own page

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_passwordvalidator#13]
* [x] add a new admin external page
* [x] make a new simple form which accepts a password, and optionally a username or email

https://docs.moodle.org/dev/Form_API

* [x] refactor the password check stuff to take a user argument

**Comment by Peterburnett** [comment]
Wrapper function for plugin calls now uses the currently logged in users. Main validation function now accepts $user object as a parameter

**Comment by Peterburnett** [comment]
Closed by PR #20
