### ISSUE TITLE
Improved feedback messages

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_passwordvalidator#35]
eg sequential_digits_input = 2

$string['responsenumericsequence'] = 'Password contains numeric sequence.';

It would be better if this was:

$string['responsenumericsequence'] = 'Password contain contain more than {$a} numeric digits ';

This applies to most of the settings which can be tuned, otherwise the user doesn't know what exactly to fix

**Comment by Peterburnett** [comment]
Closed in PR #39
