### ISSUE TITLE
Improve support for $CFG->passwordpolicy instead of removing it

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_passwordvalidator#47]
ie force these settings ON:

$CFG->passwordpolicy = 1

$CFG->minpassworddigits = 0
$CFG->minpasswordlower = 0

etc

The reason for this is because on the signup page we want to show the password policy:

https://github.com/moodle/moodle/blob/master/login/signup_form.php#L46

which calls:

https://github.com/moodle/moodle/blob/master/lib/weblib.php#L3612

So we need to add a hook there so our plugin can inject a nice message into the signup form

**Comment by brendanheywood** [comment]
fyi https://tracker.moodle.org/browse/MDL-66278

**Comment by Peterburnett** [comment]
Closed in PR #48
